// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230411002542_AddVersionColumn")]
    partial class AddVersionColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("char(36)");

                    b.HasKey("Sku");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.OwnsMany("Domain.Batch", "Batches", b1 =>
                        {
                            b1.Property<string>("Reference")
                                .HasColumnType("varchar(255)");

                            b1.Property<DateTime?>("Eta")
                                .HasColumnType("datetime(6)");

                            b1.Property<int>("PurchasedQuantity")
                                .HasColumnType("int");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.HasKey("Reference");

                            b1.HasIndex("Sku");

                            b1.ToTable("Batches", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Sku");

                            b1.OwnsMany("Domain.OrderLine", "Allocations", b2 =>
                                {
                                    b2.Property<string>("OrderId")
                                        .HasColumnType("varchar(255)");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int");

                                    b2.Property<string>("Sku")
                                        .HasColumnType("varchar(255)");

                                    b2.Property<string>("Reference")
                                        .HasColumnType("varchar(255)");

                                    b2.HasKey("OrderId", "Quantity", "Sku");

                                    b2.HasIndex("Reference");

                                    b2.ToTable("OrderLines", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("Reference");
                                });

                            b1.Navigation("Allocations");
                        });

                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
