// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220720005914_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("_eta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("eta");

                    b.Property<int>("_purchasedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("purchased_quantity");

                    b.Property<string>("_reference")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reference");

                    b.Property<string>("_sku")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("Domain.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("_orderId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("order_id");

                    b.Property<int>("_quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("_sku")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sku");

                    b.Property<int?>("batch_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("batch_id");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("Domain.OrderLine", b =>
                {
                    b.HasOne("Domain.Batch", null)
                        .WithMany("Allocations")
                        .HasForeignKey("batch_id");
                });

            modelBuilder.Entity("Domain.Batch", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
